### PR TITLE
Enable readonly

### PR DESCRIPTION
**Pull request by takoau**
1.  Add type flags in TDS packet
2.  Correct type flag in tds.py

### CODE REVIEW

**Review by ecly — APPROVED** [review]
Confirmed that this works for our usecase.

**Comment by takoau** [comment]
> Confirmed that this works for our usecase.
Hi Ecly,

I am not a developer but a DBA so I'm not familiar with coding lifecycles.  Could you tell how I can fix the codecov errors?

**Comment by takoau** [comment]
> > Confirmed that this works for our usecase.
> > Hi Ecly,
> 
> I am not a developer but a DBA so I'm not familiar with coding lifecycles. Could you tell how I can fix the codecov errors?

@ecly

**Comment by jhoareau** [comment]
Hi @takoau the coverage decreasing might not be an issue (that will have to be taken up with @denisenkom), but some tests are failing in the CI, in particular the `test_bulk_insert` raises a timeout in some environments:
https://ci.appveyor.com/project/denisenkom/pytds/builds/44202650/job/q08bnxgc7qg8tuui
https://ci.appveyor.com/project/denisenkom/pytds/builds/44202650/job/ocybqh8ujgwtkxwg
https://ci.appveyor.com/project/denisenkom/pytds/builds/44202650/job/gi8je55506nuohhg

**Comment by takoau** [comment]
> Hi @takoau the coverage decreasing might not be an issue (that will have to be taken up with @denisenkom), but some tests are failing in the CI, in particular the `test_bulk_insert` raises a timeout in some environments: https://ci.appveyor.com/project/denisenkom/pytds/builds/44202650/job/q08bnxgc7qg8tuui https://ci.appveyor.com/project/denisenkom/pytds/builds/44202650/job/ocybqh8ujgwtkxwg https://ci.appveyor.com/project/denisenkom/pytds/builds/44202650/job/gi8je55506nuohhg
> 
> However, it looks like the main author of this project has not accepted any PRs for the past year, so I am a bit worried about the future of this project. We have actually released a PyPi wheel based on your branch for our needs: https://pypi.org/project/python-tds-readonly-fork/1.11.1/

Hey @jhoareau thanks for your explanation.  To be honest I have no idea with coverage before you told me.  :)
On the other hand, I suspect the test case has some issues that, all pending PRs have the same failed cases on bulk insert timeout.
[PR#138](https://github.com/denisenkom/pytds/pull/138)
[PR#130](https://github.com/denisenkom/pytds/pull/130)

This test case went well if a new table is created.  I reverted this change yesterday as it's better not to mess up the original test cases.

```
cur.execute('create table myschema.bulk_insert_table(num int not null, data varchar(100))')
cur.copy_to(f, 'bulk_insert_table', schema='myschema', columns=('num', 'data'))
cur.execute('select num, data from myschema.bulk_insert_table')
assert [(42, 'foo'), (74, 'bar')] == cur.fetchall()
```

**Review by denisenkom — APPROVED** [review]

**Pull request merged**
