### PR TITLE
feat: add support for passing in SSL socket to connect function

### LINKED ISSUE #119: feature request: allow passing in socket to connect function
Hi, I'm one of the maintainers of the Google [Cloud SQL Python connector](https://github.com/GoogleCloudPlatform/cloud-sql-python-connector), and we're trying to add support for using pytds to connect to Cloud SQL instances. This would require using a socket that's wrapped in a custom SSL context. The easiest way to do this would be to allow passing in a socket argument to the connect function.

### PR DESCRIPTION
**Pull request by shubha-rajan**
fixes #119

### CODE REVIEW

**Comment by shubha-rajan** [comment]
Hi @denisenkom, can you please take a look at this and help me get the build passing? Happy to work with you on any changes that need to be made. Thanks!

**Comment by denisenkom** [comment]
Hi @shubha-rajan, can you rebase your change against latest master branch

**Comment by shubha-rajan** [comment]
> Hi @shubha-rajan, can you rebase your change against latest master branch

Done!

**Comment by shubha-rajan** [comment]
@denisenkom Once this is is merged, can you push a new release so we can use all the new features from the last year?

**Comment by denisenkom** [comment]
How did you test this change?

**Comment by shubha-rajan** [comment]
> How did you test this change?

I'm using the change to pass in a socket wrapped with a custom SSLContext object here: https://github.com/GoogleCloudPlatform/cloud-sql-python-connector/pull/57/files#diff-c11697acd4731dd8e801d4096039cb866c51b15df1ddf3bb68bcc69d8e714342R592

I can add tests to this PR too, if needed.

**Pull request merged**
