### PR TITLE
bug: Fixed timeout referencing EncryptedObject

### PR DESCRIPTION
**Pull request by radyz**
It's mentioned in #82

### CODE REVIEW

**Comment by denisenkom** [comment]
Thanks!

**Comment by radyz** [comment]
Hi @denisenkom , is it possible to get this published as 1.9.1 so it's available on PyPi :(

**Comment by denisenkom** [comment]
Will do

**Comment by denisenkom** [comment]
uploaded: https://pypi.python.org/pypi/python-tds/1.9.1

**Pull request merged**
