### PR TITLE
Update tds.py

### LINKED ISSUE #117: logging module
I have found it difficult to manage the logging output of pytds. A simple line change in pytds.py would help from the following:

`logger = logging.getLogger()`

changed to 

`logger = logging.getLogger('tds')`

This change would allow the following to work, where today this is ignored and the logs fill with every INFO statement.

`logging.getLogger('tds').setLevel(logging.ERROR)`

A workaround I used was the following, but its not ideal.

```
class MyFilter(logging.Filter):
    def filter(self, record):
        if record.module == "tds" and record.levelname == "INFO":
            return False
        return True
logging.getLogger().addFilter(MyFilter())
```

### PR DESCRIPTION
**Pull request by niconil**
Fix #117 : this allows programs using this module to have control on logging messages from pytds.

### CODE REVIEW

**Review by akachroo762 — APPROVED** [review]

**Comment by niconil** [comment]
what can we do to merge this change ?
no activity on this repo since May 2021 !

**Comment by tpow** [comment]
@denisenkom Can you please review and merge this and make a new release? This is causing pain for many of us using logging and looks like a simple oversight. Thanks! Tim

**Comment by denisenkom** [comment]
Thank you for the PR! I will try to release new version this weekend

**Comment by denisenkom** [comment]
New version is released: https://pypi.org/project/python-tds/1.12.0/

**Pull request merged**
