### PR TITLE
Tweak escaping of percent signs for SQLAlchemy

### PR DESCRIPTION
**Pull request by gordthompson**
Fixes: #171

### CODE REVIEW

**Comment by denisenkom** [comment]
Can you add a test case that covers this change?

**Comment by gordthompson** [comment]
> Can you add a test case that covers this change?

Done.

**Review by denisenkom — APPROVED** [review]
LGTM

**Comment by denisenkom** [comment]
@m32 does this change look good to you?

**Comment by m32** [comment]
LGTM
I've tried this topic several times and I couldn't handle it, respect

SQLAlchemy==2.0.31 tests with pytds

before this change:
50 failed, 706 passed, 777 skipped, 1 warning
after:
30 failed, 737 passed, 777 skipped, 1 warning

**Pull request merged**
